public enum Message
{
	NONE,
	PLAYER_CONNECTED,
	PLAYER_DISCONNECTED,
	PLAYER_JOIN,
	SET_GAMEMODE,
	SET_ARENA,
	START_DESERT,
	START_FOREST,
	PLAYER_SPAWN,
	START_ROUND,
	PLAYER_INPUT,
	PLAYER_PROJECTILES_STATE,
	PLAYER_SHOOT,
	PLAYER_DESTROY,
	DESTROY_PROJECTILE,
	PLAYER_TAKE_DAMAGE,
	SET_WINNER_TEAM,
	SHOW_VICTORY_SCREEN,
	SHOW_DEFEAT_SCREEN,

}