public enum Message
{
	NONE,
	PLAYER_CONNECTED,
	PLAYER_DISCONNECTED,
	PLAYER_JOIN,
	SET_GAMEMODE,
	START_MATCH,
	PLAYER_SPAWN,
	PLAYER_INPUT,
	PLAYER_PROJECTILES_STATE,
	PLAYER_SHOOT,
	DESTROY_PROJECTILE,
	PLAYER_TAKE_DAMAGE,
}